runtime: python39

handlers:

- url: /data/.*
  script: auto

- url: /(.*\.css)
  mime_type: text/css
  static_files: dist/fin-soup/browser/\1
  upload: dist/fin-soup/browser/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: dist/fin-soup/browser/\1
  upload: dist/fin-soup/browser/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: dist/fin-soup/browser/\1
  upload: dist/fin-soup/browser/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: dist/fin-soup/browser/\1
  upload: dist/fin-soup/browser/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: dist/fin-soup/browser/\1
  upload: dist/fin-soup/browser/(.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: dist/fin-soup/browser/\1
  upload: dist/fin-soup/browser/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# index files
- url: /(.+)/
  static_files: dist/fin-soup/browser/\1/index.html
  upload: dist/fin-soup/browser/(.+)/index.html

# redirect to 'url + /index.html' url.
- url: /(.+)
  static_files: dist/fin-soup/browser/redirector.html
  upload: dist/fin-soup/browser/redirector.html

# site root
- url: /
  static_files: dist/fin-soup/browser/index.html
  upload: dist/fin-soup/browser/index.html

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/PROJECT:INSTANCE
  DB_USER: USERNAME
  DB_PASS: PASSWORD
  DB_NAME: DATABASENAME
